a = ("FIO - Jann Batist Poklen")
b = ("Professiya - Akter i direktor teatra vo Francii")
c = ("Mesto Rojdeniya - Franciya")
d = ("data rojdeniya i smerti - 1622 - 1673")
print(a)
print(b)
print(c)
print(d)
input()